version: '3.4'

services:
  patientmanagementapi:
    image: ${DOCKER_REGISTRY-}patientmanagementapi
    build:
      context: .
      dockerfile: PatientManagementApi/Dockerfile
    networks:
        - mynetworks
  patientdb:
     image: postgres
     networks:
        - mynetworks
volumes:
  postgres_patient:
networks:
  mynetworks:
    name: mynetworks
    driver: bridge
